//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string _of_ {
            get {
                return ResourceManager.GetString("_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VietOCR.NET.
        /// </summary>
        internal static string About_VietOCR {
            get {
                return ResourceManager.GetString("About_VietOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no write access to &quot;{0}&quot; folder.
        ///Please run the program as administrator..
        /// </summary>
        internal static string Access_denied {
            get {
                return ResourceManager.GetString("Access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Dictionary.
        /// </summary>
        internal static string Add_to_Dictionary {
            get {
                return ResourceManager.GetString("Add_to_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process Status.
        /// </summary>
        internal static string BatchProcessStatus {
            get {
                return ResourceManager.GetString("BatchProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of task.
        /// </summary>
        internal static string Beginning_of_task {
            get {
                return ResourceManager.GetString("Beginning_of_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk OCR.
        /// </summary>
        internal static string Bulk_OCR {
            get {
                return ResourceManager.GetString("Bulk_OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Process Status.
        /// </summary>
        internal static string BulkProcessStatus {
            get {
                return ResourceManager.GetString("BulkProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Bulk OCR.
        /// </summary>
        internal static string CancelBulkOCR {
            get {
                return ResourceManager.GetString("CancelBulkOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled..
        /// </summary>
        internal static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load image..
        /// </summary>
        internal static string Cannotloadimage {
            get {
                return ResourceManager.GetString("Cannotloadimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process .
        /// </summary>
        internal static string Cannotprocess {
            get {
                return ResourceManager.GetString("Cannotprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check output file(s) in .
        /// </summary>
        internal static string check_output_in {
            get {
                return ResourceManager.GetString("check_output_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Recent Files.
        /// </summary>
        internal static string Clear_Recent_Files {
            get {
                return ResourceManager.GetString("Clear_Recent_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction completed..
        /// </summary>
        internal static string Correcting_completed {
            get {
                return ResourceManager.GetString("Correcting_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcting recognition errors....
        /// </summary>
        internal static string Correcting_errors {
            get {
                return ResourceManager.GetString("Correcting_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been created..
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes to .
        /// </summary>
        internal static string Do_you_want_to_save_the_changes_to_ {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_the_changes_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download canceled..
        /// </summary>
        internal static string Downloadcanceled {
            get {
                return ResourceManager.GetString("Downloadcanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed..
        /// </summary>
        internal static string Downloadcompleted {
            get {
                return ResourceManager.GetString("Downloadcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error..
        /// </summary>
        internal static string Downloaderror {
            get {
                return ResourceManager.GetString("Downloaderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        internal static string Elapsed_time {
            get {
                return ResourceManager.GetString("Elapsed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of task.
        /// </summary>
        internal static string End_of_task {
            get {
                return ResourceManager.GetString("End_of_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string Ignore_All {
            get {
                return ResourceManager.GetString("Ignore_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incomplete..
        /// </summary>
        internal static string Inputincomplete {
            get {
                return ResourceManager.GetString("Inputincomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input invalid..
        /// </summary>
        internal static string Inputinvalid {
            get {
                return ResourceManager.GetString("Inputinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no page numbered &apos;{0}&apos; in this image..
        /// </summary>
        internal static string InvalidPageMessage {
            get {
                return ResourceManager.GetString("InvalidPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string Load_image {
            get {
                return ResourceManager.GetString("Load_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load an image..
        /// </summary>
        internal static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading completed..
        /// </summary>
        internal static string Loading_completed {
            get {
                return ResourceManager.GetString("Loading_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image....
        /// </summary>
        internal static string Loading_image {
            get {
                return ResourceManager.GetString("Loading_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge PDF running....
        /// </summary>
        internal static string MergePDF_running {
            get {
                return ResourceManager.GetString("MergePDF_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge PDF completed. .
        /// </summary>
        internal static string MergePDFcompleted {
            get {
                return ResourceManager.GetString("MergePDFcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge TIFF running....
        /// </summary>
        internal static string MergeTIFF_running {
            get {
                return ResourceManager.GetString("MergeTIFF_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge TIFF completed. .
        /// </summary>
        internal static string MergeTIFFcompleted {
            get {
                return ResourceManager.GetString("MergeTIFFcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recent Files.
        /// </summary>
        internal static string No_Recent_Files {
            get {
                return ResourceManager.GetString("No_Recent_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR completed..
        /// </summary>
        internal static string OCRcompleted {
            get {
                return ResourceManager.GetString("OCRcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Operation.
        /// </summary>
        internal static string OCROperation {
            get {
                return ResourceManager.GetString("OCROperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR running....
        /// </summary>
        internal static string OCRrunning {
            get {
                return ResourceManager.GetString("OCRrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image File.
        /// </summary>
        internal static string OpenImageFile {
            get {
                return ResourceManager.GetString("OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page_ {
            get {
                return ResourceManager.GetString("Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the program so that it could register the new language pack(s)..
        /// </summary>
        internal static string Please_restart {
            get {
                return ResourceManager.GetString("Please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET GUI Frontend for Tesseract 3.02 OCR Engine.
        /// </summary>
        internal static string Program_desc {
            get {
                return ResourceManager.GetString("Program_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme_cs.html.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource does not exist..
        /// </summary>
        internal static string Resource_not_exist {
            get {
                return ResourceManager.GetString("Resource_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Merged PDF.
        /// </summary>
        internal static string Save_Merged_PDF {
            get {
                return ResourceManager.GetString("Save_Merged_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Multi-page TIFF Image.
        /// </summary>
        internal static string Save_Multipage_TIFF_Image {
            get {
                return ResourceManager.GetString("Save_Multipage_TIFF_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed..
        /// </summary>
        internal static string Scancompleted {
            get {
                return ResourceManager.GetString("Scancompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Operation.
        /// </summary>
        internal static string ScanningOperation {
            get {
                return ResourceManager.GetString("ScanningOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input Images.
        /// </summary>
        internal static string Select_Input_Images {
            get {
                return ResourceManager.GetString("Select_Input_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input PDFs.
        /// </summary>
        internal static string Select_Input_PDFs {
            get {
                return ResourceManager.GetString("Select_Input_PDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input Multi-page TIFF.
        /// </summary>
        internal static string Select_Input_TIFF {
            get {
                return ResourceManager.GetString("Select_Input_TIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language..
        /// </summary>
        internal static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split PDF completed..
        /// </summary>
        internal static string SplitPDF_completed {
            get {
                return ResourceManager.GetString("SplitPDF_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split PDF running....
        /// </summary>
        internal static string SplitPDF_running {
            get {
                return ResourceManager.GetString("SplitPDF_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split TIFF running....
        /// </summary>
        internal static string SplitTIFF_running {
            get {
                return ResourceManager.GetString("SplitTIFF_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split TIFF completed..
        /// </summary>
        internal static string SplitTIFFcompleted {
            get {
                return ResourceManager.GetString("SplitTIFFcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to split the PDF file into smaller files before proceed..
        /// </summary>
        internal static string suggest_split {
            get {
                return ResourceManager.GetString("suggest_split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task canceled.
        /// </summary>
        internal static string Task_canceled {
            get {
                return ResourceManager.GetString("Task_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon VietOCR {
            get {
                object obj = ResourceManager.GetObject("VietOCR", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietOCR.NET Help.
        /// </summary>
        internal static string VietOCR_Help {
            get {
                return ResourceManager.GetString("VietOCR_Help", resourceCulture);
            }
        }
    }
}
